version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test
      - run:
          name: build
          command: make build
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: deploy
          command: make deploy
workflows:
  version: 2
  build:
    jobs:
      - build:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            # No branches, version tags only.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
